steps:
# Build the container image
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/ethereal-audio-370311/myapp', '.']
# Push the container image to Container Registry
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/ethereal-audio-370311/myapp']
# Deploy container image to Cloud Run
- name: 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myapp', '--image', 'asia.gcr.io/ethereal-audio-370311/myapp', '--region', 'asia-south1', 'managed', '--port', '80']
images:
- asia.gcr.io/ethereal-audio-370311/myapp