steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ethereal-audio-370311/asia.gcr.io/ethereal-audio-370311/myapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ethereal-audio-370311/asia.gcr.io/ethereal-audio-370311/myapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'asia.gcr.io/ethereal-audio-370311/myapp', '--image', 'gcr.io/ethereal-audio-370311/asia.gcr.io/ethereal-audio-370311/myapp', '--region', 'asia-south1']
images:
- gcr.io/ethereal-audio-370311/asia.gcr.io/ethereal-audio-370311/myapp